name: default
description: Default validation profile with all levels enabled
enabled_levels:
  - WellFormed
  - XSD
  - Schematron
  - Semantic
severity_overrides:
  # No overrides by default
intake_limits:
  max_bytes: 10485760  # 10MB
  allowed_content_types:
    - application/xml
    - text/xml
  timeout_seconds: 30
